### ISSUE TITLE
Merge to Master

### ISSUE THREAD

**Issue by r-barnes** [gb4uer/RISE#8]
I'd like to figure out a way to rearrange master so that there's a path for eventually merging the mesa path into it. Any thoughts @nickolasclarke ?

**Comment by nickolasclarke** [comment]
@r-barnes honestly, at this point I think we should move into our own repo. Initially we thought that this would be more of a port of the RISE model. We've diverged significantly. We can fork or spin an empty repo. Thoughts?

**Comment by r-barnes** [comment]
Sure, an empty repo is fine if you'd like to start that. One way would be to clone this repo and then filter-branch to only the new stuff. That way we keep the commit history. Could you handle that?

**Comment by nickolasclarke** [comment]
yep, I was hoping to keep the commit history. I'll do so.

**Comment by nickolasclarke** [comment]
Moved to [nickolasclarke/dispatch](https://github.com/nickolasclarke/dispatch)
